#!/bin/sh

echo -n $0: 'End of sentence 1... '

cat >test.in <<eof
This is one 4. sentence.
eof

cat >test.ref <<eof
No phrases in 1 sentence found.
eof

sh ./test/rundiction test.in >test.data

if cmp test.ref test.data
then
  rm -f test.*
  echo passed
else
  echo failed
  exit 1
fi
